### PR TITLE
Spring Boot 3.0.x upgrade

### PR DESCRIPTION
**Pull request by ahndmal**
upgrade to Spring Boot 3..0.0

### CODE REVIEW

**Comment by ahndmal** [comment]
Hello. Should I close it ?
@OlegDokuka 
@sdeleuze 
@antonarhipov

**Comment by sdeleuze** [comment]
@AndriiMaliuta Nope, sorry for the delay, we should merge it, I can take care of take. Could you please refine the PR to avoid changing the ident and maybe use the latest Boot version?

**Comment by ahndmal** [comment]
@sdeleuze , thanks a lot! Updated the versions.

**Comment by sdeleuze** [comment]
Thanks, as requested above could you please rollback the indent change in order to have a clean diff?

**Review by sdeleuze — CHANGES_REQUESTED** [review]
Could you please rollback the indent changes in order to have a clean diff?

**Comment by ahndmal** [comment]
@sdeleuze sorry for that. Corrected the indentations :) Hope it is OK.

**Comment by sdeleuze** [comment]
No problem. As you can see in the diff, not yet ok because you still change the tabs to spaces, the goal is not have only the version changes in the diff. Maybe you need to change IDE settings to avoid automatic conversion?

image

**Comment by ahndmal** [comment]
Hello @sdeleuze,
Changed the formatting :)

**Comment by sdeleuze** [comment]
Thanks, merged via 90b9623f447d92e3a2409e6737089e5351b48646.

**Pull request closed without merging**
